name: Run Jest tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
