name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FILEN_CLI_TESTING_EMAIL: ${{ secrets.V2_TEST_ACC_EMAIL }}
      FILEN_CLI_TESTING_PASSWORD: ${{ secrets.V2_TEST_ACC_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run test