name: Update filen-docs with changes to CLI docs

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "src/interface/helpPage.ts"

jobs:
  make-filen-docs-pr:
    name: Create issue on FilenCloudDienste/filen-docs
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FILEN_DOCS_PAT }}
          script: |
            github.rest.issues.create({
              owner: 'FilenCloudDienste',
              repo: 'filen-docs',
              title: 'Update CLI docs',
              labels: ['update-cli-docs'],
              body: 'The CLI docs have been updated: ${{ github.event.head_commit.url }}',
            })