name: Run Vitest tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vitest:
    runs-on: ubuntu-latest
    env:
      FILEN_CLI_TESTING_EMAIL: ${{ secrets.V2_TEST_ACC_EMAIL }}
      FILEN_CLI_TESTING_PASSWORD: ${{ secrets.V2_TEST_ACC_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Lock and prepare testing environment
        run: npm run prepare-testing lock && npm run prepare-testing overwrite all
      - name: Run Vitest
        run: npm run test
      - name: Unlock testing environment
        run: npm run prepare-testing unlock
        if: always() # ensure the environment is unlocked even if tests fail